# Generated by Django 6.0 on 2026-04-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=80)),
                ("response", models.TextField(help_text="The text that will be displayed", max_length=2000)),
                (
                    "style",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Primary"),
                            (2, "Secondary"),
                            (3, "Success"),
                            (4, "Danger"),
                            (5, "Link"),
                            (6, "Premium"),
                        ],
                        default=2,
                        help_text="Button color",
                    ),
                ),
            ],
        )
    ]
