# Generated by Django 6.0 on 2026-09-08 16:24

import labelmaker_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labelmaker_app", "0002_label_ephemeral_alter_label_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="caught_emoji",
            field=models.CharField(
                blank=True,
                help_text="A single standard Unicode emoji for the button after a ball is caught",
                max_length=10,
                validators=[labelmaker_app.models.validate_unicode_emoji],
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="caught_label",
            field=models.CharField(
                blank=True,
                help_text="The label's text after a ball is caught",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="caught_override",
            field=models.BooleanField(
                default=False,
                help_text="Whether the label's appearance will change when a ball is caught",
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="caught_style",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Primary"),
                    (2, "Secondary"),
                    (3, "Success"),
                    (4, "Danger"),
                ],
                default=2,
                help_text="The label's button color after a ball is caught",
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="despawn_emoji",
            field=models.CharField(
                blank=True,
                help_text="A single standard Unicode emoji for the button after a ball despawns",
                max_length=10,
                validators=[labelmaker_app.models.validate_unicode_emoji],
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="despawn_label",
            field=models.CharField(
                blank=True,
                help_text="The label's text after a ball despawns",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="despawn_override",
            field=models.BooleanField(
                default=False,
                help_text="Whether the label's appearance will change when a ball despawns",
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="despawn_style",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Primary"),
                    (2, "Secondary"),
                    (3, "Success"),
                    (4, "Danger"),
                ],
                default=2,
                help_text="The label's button color after a ball despawns",
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="emoji",
            field=models.CharField(
                blank=True,
                help_text="A single standard Unicode emoji for the button",
                max_length=10,
                validators=[labelmaker_app.models.validate_unicode_emoji],
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="enabled",
            field=models.BooleanField(
                default=True, help_text="Whether the label will appear"
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="ephemeral",
            field=models.BooleanField(
                default=False,
                help_text="Whether the label will only be visible to the user who interacted with it.",
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="label",
            field=models.CharField(help_text="The label's text", max_length=80),
        ),
        migrations.AlterField(
            model_name="label",
            name="response",
            field=models.TextField(
                help_text="The response that will be sent after pressing the label's button",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="style",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Primary"),
                    (2, "Secondary"),
                    (3, "Success"),
                    (4, "Danger"),
                ],
                default=2,
                help_text="The label's button color",
            ),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("despawn_override", True), _negated=True),
                    models.Q(("despawn_label", ""), _negated=True),
                    _connector="OR",
                ),
                name="despawn_label_required_if_override",
            ),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("caught_override", True), _negated=True),
                    models.Q(("caught_label", ""), _negated=True),
                    _connector="OR",
                ),
                name="caught_label_required_if_override",
            ),
        ),
    ]
